version: '3.0'
services:
  ocserv: 
    image: tommylau/ocserv
    restart: always
    container_name: ocserv
    privileged: true
    hostname: proxy1.o.com
    ports:
        - '443:443/udp'
        - '443:443'
    volumes:
        - '/opt/docker/ocserv/ocserv:/etc/ocserv'
    environment:
        - CA_CN=proxy1.o.com
        - CA_ORG=o
        - CA_DAYS=3650
        - SRV_CN=proxy1.o.com
        - SRV_ORG=o
        - SRV_DAYS=365
        - NO_TEST_USER=1


