version: "3"
services:
  nginx:
    image: nginx:1.13
    restart: always
    volumes:
      - /storage:/usr/share/nginx/html:ro
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80

  apt-mirror-main:
    build: .
    restart: always
    volumes:
      - ./conf/mirror-main.list:/etc/apt/mirror-main.list:ro
      - ./conf/mirror-thirdparty.list:/etc/apt/mirror-thirdparty.list:ro
      - /storage:/var/spool/apt-mirror/
    environment:
      - PROXY_SERVER=pxuser:devops@proxy.d.com:7777
