network: 
  version: 2
  ethernets:
    eth0:
        dhcp4: no
        addresses: [{{ ansible_eth0.ipv4.address }}/16]
        gateway4: 192.168.200.35
        mtu: 1442
        set-name: eth0
        match:
            macaddress: {{ ansible_eth0.macaddress  }}

