global:
 scrape_interval: 15s
 evaluation_interval: 15s

alerting:
 alertmanagers:
  - static_configs:
    - targets:
      - "localhost:9093"

rule_files:
  - "prometheus.rules.yml"

scrape_configs:
   - job_name: 'haproxy'
     metrics_path: /metrics
     static_configs:
       - targets:
          - app-prod1.example.com:9101
          - app-stg.example.com:9101
   - job_name: 'nginx'
     metrics_path: /metrics
     static_configs:
      - targets:
         - app-prod1.example.com:9113
         - app-stg.example.com:9113
   - job_name: 'node-exporter'
     metrics_path: /metrics
     static_configs:
      - targets:
         - app-stg.example.com:9100
         - app-prod1.example.com:9100
   - job_name: 'redis'
     metrics_path: /metrics
     static_configs:
      - targets:
         - app-prod1.example.com:9121
         - app-stg.example.com:9121
   - job_name: 'mongodb'
     metrics_path: /metrics
     static_configs:
      - targets:
         - app-prod1.example.com:9001
   - job_name: 'blackbox'
     metrics_path: /probe
     params:
       module: [http_2xx]
     static_configs:
       - targets:
               - http://app-prod1.example.com:3001/check
               - https://test.net
     relabel_configs:
       - source_labels: [__address__]
         target_label: __param_target
       - source_labels: [__param_target]
         target_label: instance
       - target_label: __address__
         replacement: localhost:9115

#   - job_name: alerta
#     metrics_path: /api/management/metrics
#     static_configs:
#      - targets:
#         - alerta:8080      
#      basic_auth:
#        username: admin@alerta.io
#        password: alerta
