---
- name: example play
  hosts: all
  gather_facts: false
  tasks:
    - name: copy head file for resolvconf 
      copy: src=templates/head  dest=/etc/resolv.conf

    - name: Disabling SELinux state
      selinux:
       state: disabled

    - name: Disabling SELinux state2
      shell: setenforce 0

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Update all installed packages using YUM module
      yum:
        name: '*'
        state: latest
        update_cache: yes
        update_only: yes
      register: yum_update_status

    - name: Remove packates not needed anymore
      yum:
        autoremove: yes



