version: '3.0'
services:
  prometheus:
    image: prom/prometheus
    network_mode: host
    volumes:
      - /opt/docker/prom-grafana/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/docker/prom-grafana/config/prometheus/prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml
      - /opt/docker/prom-grafana/data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=http://172.16.95.20/prom'
      - '--web.enable-admin-api'
    ports:
      - '9090:9090'
    extra_hosts:
      app-prod1.example.com: 172.16.95.19     
      app-stg.example.com: 172.16.95.20
    depends_on:
      - alertmanager
    restart: always

  grafana:
    image: grafana/grafana
    network_mode: host
    volumes:
      - /opt/docker/prom-grafana/config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /opt/docker/prom-grafana/data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=mypssword
    depends_on:
      - prometheus
    ports:
      - "3000:3000"


  alertmanager:
    image: prom/alertmanager
    network_mode: host
    volumes:
      - ./config/alertmanager:/prometheus
      - ./data/alertmanager:/data
    command:
      - '--config.file=/prometheus/alertmanager.yml'
      - '--storage.path=/data'
    ports:
      - 9093:9093

  node:
    image: prom/node-exporter
    network_mode: host
    ports:
      - 9100:9100
    restart: always

  blackbox:
    image: bitnami/blackbox-exporter
    network_mode: host
    volumes:
      - /opt/docker/prom-grafana/config/blackbox/config.yml:/opt/bitnami/blackbox-exporter/conf/config.yml
    ports:
      - 9115:9115
    extra_hosts:
      app-prod1.example.com: 172.16.95.19     
    restart: always

